local_repository(
  name = "org_tensorflow",
  path = "../tensorflow-0.10.0",
)

load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace("../tensorflow-0.10.0/", "@org_tensorflow")

# Specify the minimum required Bazel version.
load("@org_tensorflow//tensorflow:tensorflow.bzl", "check_version")
check_version("0.3.0")
